// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelJob(arg1:string):Promise<boolean>;

export function CheckOpenRouterAPIKey():Promise<main.OpenRouterKeyStatus>;

export function CreateConfigFile(arg1:string):Promise<string>;

export function GenerateNames(arg1:string):Promise<void>;

export function GetAIStatus():Promise<main.AIStatus>;

export function GetAnalytics():Promise<main.AnalyticsSummary>;

export function GetConfig():Promise<main.DesktopConfig>;

export function GetConfigPath():Promise<string>;

export function GetHistory():Promise<Array<main.Session>>;

export function GetJobStatus(arg1:string):Promise<main.JobStatus>;

export function GetPlan(arg1:string):Promise<Array<main.RenameEntry>>;

export function OpenFile(arg1:string):Promise<void>;

export function RunJob(arg1:string,arg2:main.RunJobOptions):Promise<string>;

export function SaveConfig(arg1:main.DesktopConfig):Promise<boolean>;

export function ScanDirectory(arg1:string):Promise<string>;

export function SelectConfigFile(arg1:string):Promise<string>;

export function SelectFolder(arg1:string):Promise<string>;

export function SetConfigPath(arg1:string):Promise<main.DesktopConfig>;

export function TestOpenRouterAPIKey(arg1:string,arg2:string):Promise<main.OpenRouterTestResult>;
