// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function CheckOpenRouterAPIKey() {
  return window['go']['main']['App']['CheckOpenRouterAPIKey']();
}

export function CreateConfigFile(arg1) {
  return window['go']['main']['App']['CreateConfigFile'](arg1);
}

export function GenerateNames(arg1) {
  return window['go']['main']['App']['GenerateNames'](arg1);
}

export function GetAIStatus() {
  return window['go']['main']['App']['GetAIStatus']();
}

export function GetAnalytics() {
  return window['go']['main']['App']['GetAnalytics']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetJobStatus(arg1) {
  return window['go']['main']['App']['GetJobStatus'](arg1);
}

export function GetPlan(arg1) {
  return window['go']['main']['App']['GetPlan'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RunJob(arg1, arg2) {
  return window['go']['main']['App']['RunJob'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SelectConfigFile(arg1) {
  return window['go']['main']['App']['SelectConfigFile'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SetConfigPath(arg1) {
  return window['go']['main']['App']['SetConfigPath'](arg1);
}

export function TestOpenRouterAPIKey(arg1, arg2) {
  return window['go']['main']['App']['TestOpenRouterAPIKey'](arg1, arg2);
}
